### ISSUE TITLE
Please label the repo with "neo6502"

### ISSUE THREAD

**Issue by euneuber** [OLIMEX/Neo6502#1]
In order to make all projects (repos) for the Neo6502 easier to find, add a label "neo6502" to this repo and encourage all the makers to also add this label if their repo is also for the Neo6502.

Maybe add this to the README.md ?

**Comment by TsvetanUsunov** [comment]
do you mean "topic"?

**Comment by euneuber** [comment]
No, just as you did for the agon-light:

![grafik](https://github.com/OLIMEX/Neo6502/assets/3296589/1bc064ad-b0b4-4f47-b3c4-2eb72b71015f)

I think GitHub calls this a "label"
